[build]
  command = "npm install && mkdir -p dist && npm run build && cp index.html dist/ && ls -la dist/ && echo 'Files in dist:' && cat dist/bundle.js"
  publish = "dist"

[build.environment]
  NODE_VERSION = "16"